export type Lang = "en" | "hi" | "kok" | "mr";

export const copy = {
  en: {
    brand: "Susegad",
    tagline: "Ask in English, Hindi, Hinglish, Marathi, or Konkani.",
    mood: "The slow, easy feeling of a Goan afternoon.",
    about: "A chat app for India.",
    creditBefore: "Made by ",
    creditName: "Luqman",
    creditAfter: ", Class 8, PM SHRI School Kalay, Goa.",
    madeBefore: "Designed and developed by ",
    madeName: "Luqman",
    madeStudio: "CoastalCode",
    madeAfter: " in Goa",
    newChat: "New chat",
    chats: "Chats",
    emptyTitle: "How can Susegad help?",
    placeholder: "Message Susegad",
    send: "Send",
    stop: "Stop",
    delete: "Delete chat",
    menu: "Open chats",
    close: "Close",
    back: "Back",
    language: "हिंदी",
    thinking: "Susegad is thinking",
    busy: "Susegad is busy. Please try again.",
    unavailable: "Susegad is unavailable right now. Please try again.",
    limitTitle: "Daily limit reached",
    limitBody:
      "You have used today's free messages. The limit resets at midnight IST.",
    tooLong: "That message is too long. Shorten it and try again.",
    untitled: "New chat",
    you: "You",
    footer: "Free messages reset at midnight IST",
    remaining: "{count} messages left today",
    copy: "Copy",
    copied: "Copied",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    regenerate: "Try again",
    followLabel: "Ask next",
    moreIdeas: "New ideas",
    photo: "Photo",
    listening: "Listening",
    voice: "Voice",
    voiceStop: "Stop voice",
    voiceFailed: "Voice typing works in Chrome or Edge.",
    listen: "Listen",
    listenStop: "Stop",
    shorter: "Shorter",
    shorterPrompt: "Say that again in fewer, simpler words.",
    classFive: "Like Class 5",
    classFivePrompt: "Explain your last answer for a Class 5 student in India. Use short sentences and one simple example.",
    otherLanguage: "In Hindi",
    translatePrompt: "Rewrite your last answer in Hindi.",
    whatsapp: "WhatsApp",
    draw: "Draw",
    drawing: "Drawing your picture",
    drawReady: "Here is the picture.",
    drawFailed: "The picture did not finish. Please try again.",
    imageLimit: "Today's free drawings are used up. They reset at midnight IST.",
    drawPlaceholder: "Describe a picture",
    photoFailed: "Choose a smaller photo and try again.",
    lookPrompt: "Look at this picture.",
    download: "Download",
    quiz: "Quiz me",
    quizStart: "Quiz me",
    quizStartTopic: "Quiz me on {topic}",
    quizPhoto: "Quiz me on this homework",
    quizOnThis: "Quiz me on this",
    quizPlaceholder: "What should the quiz be about?",
    quizMaths: "Maths",
    quizScience: "Science",
    quizEnglish: "English",
    quizHindi: "Hindi",
    quizGk: "General knowledge",
    quizQuestion: "Question {ask} of {total}",
    quizRight: "Right",
    quizWrong: "Not quite",
    quizDone: "Quiz finished",
    quizScore: "{score} of {total}",
    quizHint: "Hint",
    quizHideHint: "Hide hint",
    quizClass5: "Class 5",
    quizClass8: "Class 8",
    quizClass10: "Class 10",
    shelf: "More",
    quizTrueFalse: "True or false",
    quizMissedAll: "Quiz these again",
    quizMissedTopic: "questions I got wrong",
    scores: "Quiz scores",
    emptyScores: "Finished quizzes appear here.",
    calc: "Calculator",
    calcNote: "Counted on this phone. This does not use a message.",
    calcShow: "Show",
    calcCheck: "Check the numbers and try again.",
    calcRupees: "Rupees in words",
    calcInterest: "Simple interest",
    calcProfit: "Profit and loss",
    calcAverage: "Average",
    calcGst: "GST",
    calcEmi: "EMI",
    calcCurrency: "Currency",
    calcFrom: "From",
    calcTo: "To",
    calcRateDate: "European Central Bank, {date}",
    calcRates: "Rates are not available right now.",
    calcHcf: "HCF and LCM",
    calcFraction: "Fractions",
    calcRatio: "Ratio",
    calcDiscount: "Discount",
    calcArea: "Area and perimeter",
    calcSpeed: "Speed, distance, time",
    calcTable: "Tables",
    calcPercent: "Percentage",
    calcAge: "Age",
    calcSplit: "Split the bill",
    calcUnits: "Units",
    calcFactors: "Factors",
    calcPowers: "Squares and cubes",
    calcRoman: "Roman numbers",
    calcPercentOf: "Percent of an amount",
    calcWhatPercent: "What percent",
    calcPart: "Part",
    calcWhole: "Whole",
    calcPeople: "People",
    calcTip: "Tip %",
    calcBirthday: "Date of birth",
    calcUnitLength: "Centimetres and metres",
    calcUnitMass: "Grams and kilograms",
    calcUnitVolume: "Millilitres and litres",
    calcUnitTemp: "Celsius and Fahrenheit",
    calcAmount: "Amount",
    calcPrincipal: "Principal",
    calcRate: "Rate %",
    calcYears: "Years",
    calcMonths: "Months",
    calcCost: "Cost price",
    calcSelling: "Selling price",
    calcNumbers: "Numbers, separated by commas",
    calcInclusive: "Amount includes GST",
    calcFirst: "First number",
    calcSecond: "Second number",
    calcNumerator: "Top",
    calcDenominator: "Bottom",
    calcAdd: "Add",
    calcSubtract: "Subtract",
    calcMultiply: "Multiply",
    calcDivide: "Divide",
    calcShare: "Amount to share",
    calcMarked: "Marked price",
    calcOff: "Discount %",
    calcRectangle: "Rectangle",
    calcSquare: "Square",
    calcCircle: "Circle",
    calcTriangle: "Triangle",
    calcLength: "Length",
    calcWidth: "Width",
    calcSide: "Side",
    calcRadius: "Radius",
    calcBase: "Base",
    calcHeight: "Height",
    calcFindSpeed: "Find speed",
    calcFindDistance: "Find distance",
    calcFindTime: "Find time",
    calcDistance: "Distance (km)",
    calcTime: "Time (hours)",
    calcSpeedValue: "Speed (km/h)",
    calcTableOf: "Table of",
    resultInterest: "Interest",
    resultAmount: "Amount",
    resultProfit: "Profit",
    resultLoss: "Loss",
    resultTotal: "Total",
    resultBase: "Before GST",
    resultMonthly: "Each month",
    resultOff: "Discount",
    resultSale: "Sale price",
    resultArea: "Area",
    resultPerimeter: "Perimeter",
    resultYears: "Years",
    resultMonths: "Months",
    resultEach: "Each person",
    resultFactors: "Factors",
    resultSquare: "Square",
    resultCube: "Cube",
    resultRoman: "Roman",
    timer: "Study timer",
    timerNote: "Counts down on this phone. This does not use a message.",
    timerMinutes: "Minutes",
    timerStart: "Start",
    timerPause: "Pause",
    timerReset: "Reset",
    timerDone: "Time is up.",
    lofi: "Lofi",
    musicRain: "Rain",
    musicPiano: "Piano",
    musicWaves: "Waves",
    musicNight: "Night",
    musicBells: "Bells",
    flashcards: "Flashcards",
    flashEmpty: "Missed quiz questions become cards.",
    flashFlip: "Flip",
    shareHolidays: "Share holidays",
    textSize: "Text size",
    textSmall: "Small",
    textMedium: "Medium",
    textLarge: "Large",
    missed: "Try these again",
    emptyMissed: "Missed quiz questions appear here.",
    retryMiss: "Quiz this again",
    deleteMiss: "Remove question",
    holidays: "Holidays",
    holidayNote: "2026 national holidays and Goa school breaks.",
    shareNote: "Share note",
    printNote: "Print note",
    note: "Save note",
    noteSaved: "Note saved",
    notes: "Notes",
    emptyNotes: "Saved notes appear here.",
    deleteNote: "Delete note",
    exportChat: "Export chat",
    sources: "Sources",
    searchChats: "Search chats",
    rename: "Rename",
    pin: "Pin",
    unpin: "Unpin",
    install: "Install on your phone",
    installShort: "Install",
    installIos: "On iPhone, tap Share, then Add to Home Screen.",
  },
  hi: {
    brand: "सुसेगाद",
    tagline: "हिंदी, अंग्रेज़ी, हिंग्लिश, मराठी या कोंकणी में पूछें।",
    mood: "गोवा की एक धीमी, आसान दोपहर का एहसास।",
    about: "भारत के लिए एक चैट ऐप।",
    creditBefore: "",
    creditName: "लुकमान",
    creditAfter: " ने बनाया, कक्षा 8, PM SHRI स्कूल कालय, गोवा।",
    madeBefore: "",
    madeName: "लुकमान",
    madeStudio: "CoastalCode",
    madeAfter: " ने गोवा में डिज़ाइन और डेवलप किया",
    newChat: "नई बातचीत",
    chats: "बातचीत",
    emptyTitle: "सुसेगाद कैसे मदद करे?",
    placeholder: "सुसेगाद को संदेश लिखें",
    send: "भेजें",
    stop: "रोकें",
    delete: "बातचीत हटाएँ",
    menu: "बातचीत खोलें",
    close: "बंद करें",
    back: "वापस",
    language: "कोंकणी",
    thinking: "सुसेगाद सोच रहा है",
    busy: "सुसेगाद अभी व्यस्त है। फिर कोशिश करें।",
    unavailable: "सुसेगाद अभी उपलब्ध नहीं है। फिर कोशिश करें।",
    limitTitle: "आज की सीमा पूरी हो गई",
    limitBody:
      "आज के मुफ़्त संदेश खत्म हो गए। सीमा आधी रात IST पर रीसेट होती है।",
    tooLong: "यह संदेश बहुत लंबा है। छोटा करके फिर भेजें।",
    untitled: "नई बातचीत",
    you: "आप",
    footer: "मुफ़्त संदेश आधी रात IST पर रीसेट होते हैं",
    remaining: "आज {count} संदेश बचे हैं",
    copy: "कॉपी",
    copied: "कॉपी हो गया",
    edit: "बदलें",
    save: "सहेजें",
    cancel: "रद्द",
    regenerate: "फिर से लिखो",
    followLabel: "आगे पूछें",
    moreIdeas: "नए सुझाव",
    photo: "फोटो",
    listening: "सुन रहा है",
    voice: "बोलें",
    voiceStop: "आवाज़ रोकें",
    voiceFailed: "आवाज़ से लिखना Chrome या Edge में चलता है।",
    listen: "सुनो",
    listenStop: "रोकें",
    shorter: "छोटा",
    classFive: "कक्षा 5 जैसा",
    classFivePrompt: "अपना पिछला जवाब भारत की कक्षा 5 के विद्यार्थी के लिए समझाओ। छोटे वाक्य और एक आसान उदाहरण दो।",
    shorterPrompt: "इसे फिर से कम और आसान शब्दों में कहो।",
    otherLanguage: "English",
    translatePrompt: "अपना पिछला जवाब अंग्रेज़ी में लिखो।",
    whatsapp: "WhatsApp",
    draw: "चित्र",
    drawing: "चित्र बन रहा है",
    drawReady: "यह रही तस्वीर।",
    drawFailed: "चित्र पूरा नहीं हुआ। फिर कोशिश करें।",
    imageLimit: "आज के मुफ़्त चित्र खत्म हो गए। सीमा आधी रात IST पर रीसेट होती है।",
    drawPlaceholder: "चित्र का वर्णन लिखें",
    photoFailed: "छोटी फोटो चुनकर फिर कोशिश करें।",
    lookPrompt: "इस तस्वीर को देखो।",
    download: "डाउनलोड",
    quiz: "क्विज़ लो",
    quizStart: "क्विज़ लो",
    quizStartTopic: "{topic} पर क्विज़ लो",
    quizPhoto: "इस होमवर्क पर क्विज़ लो",
    quizOnThis: "इसी पर क्विज़ लो",
    quizPlaceholder: "क्विज़ किस बारे में हो?",
    quizMaths: "गणित",
    quizScience: "विज्ञान",
    quizEnglish: "अंग्रेज़ी",
    quizHindi: "हिंदी",
    quizGk: "सामान्य ज्ञान",
    quizQuestion: "सवाल {ask} / {total}",
    quizRight: "सही",
    quizWrong: "अभी नहीं",
    quizDone: "क्विज़ खत्म",
    quizScore: "{score} / {total}",
    quizHint: "संकेत",
    quizHideHint: "संकेत छिपाएँ",
    quizClass5: "कक्षा 5",
    quizClass8: "कक्षा 8",
    quizClass10: "कक्षा 10",
    shelf: "और",
    quizTrueFalse: "सही या गलत",
    quizMissedAll: "गलत सवाल फिर लो",
    quizMissedTopic: "जो सवाल गलत हुए",
    scores: "क्विज़ अंक",
    emptyScores: "पूरे हुए क्विज़ यहाँ दिखेंगे।",
    calc: "कैलकुलेटर",
    calcNote: "यह फोन पर गिना जाता है। इसमें संदेश नहीं लगता।",
    calcShow: "दिखाओ",
    calcCheck: "अंक जाँचकर फिर कोशिश करो।",
    calcRupees: "रुपयों में शब्द",
    calcInterest: "साधारण ब्याज",
    calcProfit: "लाभ और हानि",
    calcAverage: "औसत",
    calcGst: "GST",
    calcEmi: "EMI",
    calcCurrency: "मुद्रा",
    calcFrom: "से",
    calcTo: "में",
    calcRateDate: "यूरोपीय सेंट्रल बैंक, {date}",
    calcRates: "दरें अभी उपलब्ध नहीं हैं।",
    calcHcf: "HCF और LCM",
    calcFraction: "भिन्न",
    calcRatio: "अनुपात",
    calcDiscount: "छूट",
    calcArea: "क्षेत्रफल और परिमाप",
    calcSpeed: "चाल, दूरी, समय",
    calcTable: "पहाड़े",
    calcPercent: "प्रतिशत",
    calcAge: "उम्र",
    calcSplit: "बिल बाँटो",
    calcUnits: "इकाइयाँ",
    calcFactors: "गुणनखंड",
    calcPowers: "वर्ग और घन",
    calcRoman: "रोमन संख्या",
    calcPercentOf: "राशि का प्रतिशत",
    calcWhatPercent: "कितना प्रतिशत",
    calcPart: "भाग",
    calcWhole: "पूरा",
    calcPeople: "लोग",
    calcTip: "टिप %",
    calcBirthday: "जन्म तिथि",
    calcUnitLength: "सेन्टीमीटर और मीटर",
    calcUnitMass: "ग्राम और किलोग्राम",
    calcUnitVolume: "मिलीलीटर और लीटर",
    calcUnitTemp: "सेल्सियस और फारेनहाइट",
    calcAmount: "रकम",
    calcPrincipal: "मूलधन",
    calcRate: "दर %",
    calcYears: "वर्ष",
    calcMonths: "महीने",
    calcCost: "क्रय मूल्य",
    calcSelling: "विक्रय मूल्य",
    calcNumbers: "अंक, अल्पविराम से अलग",
    calcInclusive: "रकम में GST शामिल है",
    calcFirst: "पहला अंक",
    calcSecond: "दूसरा अंक",
    calcNumerator: "अंश",
    calcDenominator: "हर",
    calcAdd: "जोड़",
    calcSubtract: "घटाव",
    calcMultiply: "गुणा",
    calcDivide: "भाग",
    calcShare: "बाँटने की रकम",
    calcMarked: "अंकित मूल्य",
    calcOff: "छूट %",
    calcRectangle: "आयत",
    calcSquare: "वर्ग",
    calcCircle: "वृत्त",
    calcTriangle: "त्रिभुज",
    calcLength: "लंबाई",
    calcWidth: "चौड़ाई",
    calcSide: "भुजा",
    calcRadius: "त्रिज्या",
    calcBase: "आधार",
    calcHeight: "ऊँचाई",
    calcFindSpeed: "चाल निकालो",
    calcFindDistance: "दूरी निकालो",
    calcFindTime: "समय निकालो",
    calcDistance: "दूरी (किमी)",
    calcTime: "समय (घंटे)",
    calcSpeedValue: "चाल (किमी/घंटा)",
    calcTableOf: "पहाड़ा",
    resultInterest: "ब्याज",
    resultAmount: "मिश्रधन",
    resultProfit: "लाभ",
    resultLoss: "हानि",
    resultTotal: "कुल",
    resultBase: "GST से पहले",
    resultMonthly: "हर महीना",
    resultOff: "छूट",
    resultSale: "बिक्री मूल्य",
    resultArea: "क्षेत्रफल",
    resultPerimeter: "परिमाप",
    resultYears: "वर्ष",
    resultMonths: "महीने",
    resultEach: "हर व्यक्ति",
    resultFactors: "गुणनखंड",
    resultSquare: "वर्ग",
    resultCube: "घन",
    resultRoman: "रोमन",
    timer: "पढ़ाई का समय",
    timerNote: "यह फोन पर गिना जाता है। इसमें संदेश नहीं लगता।",
    timerMinutes: "मिनट",
    timerStart: "शुरू",
    timerPause: "रोको",
    timerReset: "फिर से",
    timerDone: "समय पूरा हुआ।",
    lofi: "लोफाई",
    musicRain: "बारिश",
    musicPiano: "पियानो",
    musicWaves: "लहरें",
    musicNight: "रात",
    musicBells: "घंटी",
    flashcards: "फ्लैशकार्ड",
    flashEmpty: "गलत प्रश्न कार्ड बनेंगे।",
    flashFlip: "पलटो",
    shareHolidays: "छुट्टियाँ भेजो",
    textSize: "अक्षर का आकार",
    textSmall: "छोटा",
    textMedium: "मध्यम",
    textLarge: "बड़ा",
    missed: "ये फिर पूछो",
    emptyMissed: "गलत हुए सवाल यहाँ दिखेंगे।",
    retryMiss: "यह सवाल फिर लो",
    deleteMiss: "सवाल हटाएँ",
    holidays: "छुट्टियाँ",
    holidayNote: "2026 की राष्ट्रीय छुट्टियाँ और गोवा की स्कूल छुट्टियाँ।",
    shareNote: "नोट भेजें",
    printNote: "नोट छापें",
    note: "नोट सहेजें",
    noteSaved: "नोट सहेज लिया",
    notes: "नोट",
    emptyNotes: "सहेजे नोट यहाँ दिखेंगे।",
    deleteNote: "नोट हटाएँ",
    exportChat: "बातचीत सहेजें",
    sources: "स्रोत",
    searchChats: "बातचीत खोजें",
    rename: "नाम बदलें",
    pin: "पिन",
    unpin: "पिन हटाएँ",
    install: "फ़ोन पर इंस्टॉल करें",
    installShort: "इंस्टॉल",
    installIos: "iPhone पर Share दबाएँ, फिर Add to Home Screen चुनें।",
  },
  kok: {
    brand: "सुसेगाद",
    tagline: "इंग्लीश, हिंदी, हिंग्लिश, मराठी वा कोंकणींत विचारात.",
    mood: "गोंयच्या एका सावकाश दुपारीचो भाव.",
    about: "भारता खातीर एक चॅट अॅप.",
    creditBefore: "",
    creditName: "लुक्मान",
    creditAfter: " हाणें केलां, इयत्ता 8, PM SHRI स्कूल काळाय, गोंय.",
    madeBefore: "",
    madeName: "लुक्मान",
    madeStudio: "CoastalCode",
    madeAfter: " हाणें गोंयांत डिझाइन आनी डेव्हलप केलां",
    newChat: "नवी गप्प",
    chats: "गप्पा",
    emptyTitle: "सुसेगाद कशी मदत करूं?",
    placeholder: "सुसेगादक संदेश बरयात",
    send: "धाडात",
    stop: "थांबोयात",
    delete: "गप्प काडात",
    menu: "गप्पा उगडात",
    close: "बंद",
    back: "परत",
    language: "मराठी",
    thinking: "सुसेगाद विचारता",
    busy: "सुसेगाद आतां व्यस्त आसा. परत प्रयत्न करात.",
    unavailable: "सुसेगाद आतां उपलब्ध ना. परत प्रयत्न करात.",
    limitTitle: "आयची मर्यादा सोपली",
    limitBody: "आयचे फुकट संदेश सोपले. मर्यादा मध्यान रात IST चेरी रीसेट जाता.",
    tooLong: "हो संदेश खूब लांब आसा. ल्हान करून परत धाडात.",
    untitled: "नवी गप्प",
    you: "तुमी",
    footer: "फुकट संदेश मध्यान रात IST चेरी रीसेट जातात",
    remaining: "आय {count} संदेश उरले",
    copy: "कॉपी",
    copied: "कॉपी जालें",
    edit: "बदलात",
    save: "सेव",
    cancel: "रद्द",
    regenerate: "परतून बरयात",
    followLabel: "फुडें विचारात",
    moreIdeas: "नवे विचार",
    photo: "फोटो",
    listening: "आयकता",
    voice: "उलोयात",
    voiceStop: "आवाज थांबोयात",
    voiceFailed: "आवाजान बरोवप Chrome वा Edge हातूंत चलता.",
    listen: "आयकात",
    listenStop: "थांबोयात",
    shorter: "ल्हान",
    classFive: "इयत्ता 5 सारकें",
    classFivePrompt: "तुमचो निमाणो जाप गोंयाच्या इयत्ता 5 च्या विद्यार्थ्याक समजात. ल्हान वाक्य आनी एक सोपो उदाहरण दियात.",
    shorterPrompt: "हें परत कमी आनी सोप्या उतरांनी सांगात.",
    otherLanguage: "हिंदी",
    translatePrompt: "तुमचो निमाणो जाप हिंदींत बरयात.",
    whatsapp: "WhatsApp",
    draw: "चित्र",
    drawing: "चित्र तयार जाता",
    drawReady: "हें घे चित्र.",
    drawFailed: "चित्र पुराय जालें ना. परत प्रयत्न करात.",
    imageLimit: "आयचीं फुकट चित्रां सोपलीं. मर्यादा मध्यान रात IST चेरी रीसेट जाता.",
    drawPlaceholder: "चित्राचें वर्णन बरयात",
    photoFailed: "ल्हान फोटो वेंचून परत प्रयत्न करात.",
    lookPrompt: "ही तस्वीर पळयात.",
    download: "डाउनलोड",
    quiz: "प्रश्नमाला",
    quizStart: "प्रश्नमाला",
    quizStartTopic: "{topic} विशीं प्रश्नमाला",
    quizPhoto: "ह्या होमवर्काचेर प्रश्नमाला",
    quizOnThis: "हाचेर प्रश्नमाला",
    quizPlaceholder: "प्रश्नमाला कश्या विशीं जावं?",
    quizMaths: "गणित",
    quizScience: "विज्ञान",
    quizEnglish: "इंग्लीश",
    quizHindi: "हिंदी",
    quizGk: "सामान्य ज्ञान",
    quizQuestion: "प्रश्न {ask} / {total}",
    quizRight: "बरोबर",
    quizWrong: "चूक",
    quizDone: "प्रश्नमाला सोपली",
    quizScore: "{score} / {total}",
    quizHint: "इशारो",
    quizHideHint: "इशारो लपवात",
    quizClass5: "इयत्ता 5",
    quizClass8: "इयत्ता 8",
    quizClass10: "इयत्ता 10",
    shelf: "आनीक",
    quizTrueFalse: "खरे वा खोटे",
    quizMissedAll: "चुकीचीं परत घेयात",
    quizMissedTopic: "जीं प्रश्न चुकीं जालीं",
    scores: "प्रश्नमालेचे गुण",
    emptyScores: "सोपिल्ली प्रश्नमाला हांगा दिसतली.",
    calc: "कॅल्क्युलेटर",
    calcNote: "हें फोनाचेर मेजतात. हाका संदेश लागतना.",
    calcShow: "दाखयात",
    calcCheck: "आंकडे तपासात आनी परत यत्न करात.",
    calcRupees: "रुपयांनी उतरां",
    calcInterest: "साधो व्याज",
    calcProfit: "नफा आनी तोटो",
    calcAverage: "सरासरी",
    calcGst: "GST",
    calcEmi: "EMI",
    calcCurrency: "चलन",
    calcFrom: "हांतलें",
    calcTo: "हांत",
    calcRateDate: "युरोपियन सेंट्रल बँक, {date}",
    calcRates: "दर आत्तां मेळनात.",
    calcHcf: "HCF आनी LCM",
    calcFraction: "अपूर्णांक",
    calcRatio: "गुणोत्तर",
    calcDiscount: "सूट",
    calcArea: "क्षेत्रफळ आनी परिमिती",
    calcSpeed: "वेग, अंतर, वेळ",
    calcTable: "पाढे",
    calcPercent: "टक्केवारी",
    calcAge: "पिराय",
    calcSplit: "बिल वांटात",
    calcUnits: "एकक",
    calcFactors: "अवयव",
    calcPowers: "वर्ग आनी घन",
    calcRoman: "रोमन आंकडे",
    calcPercentOf: "रकमेची टक्केवारी",
    calcWhatPercent: "कितली टक्केवारी",
    calcPart: "भाग",
    calcWhole: "पूर्ण",
    calcPeople: "लोक",
    calcTip: "टिप %",
    calcBirthday: "जन्म तारीख",
    calcUnitLength: "सेंटीमीटर आनी मीटर",
    calcUnitMass: "ग्राम आनी किलोग्राम",
    calcUnitVolume: "मिलीलिटर आनी लिटर",
    calcUnitTemp: "सेल्सियस आनी फारेनहाइट",
    calcAmount: "रक्कम",
    calcPrincipal: "मुद्दल",
    calcRate: "दर %",
    calcYears: "वर्सां",
    calcMonths: "म्हयने",
    calcCost: "खरेदी किंमत",
    calcSelling: "विक्री किंमत",
    calcNumbers: "आंकडे, स्वल्पविरामान अंतर",
    calcInclusive: "रक्कमेंत GST आसा",
    calcFirst: "पयलो आंकडो",
    calcSecond: "दुसरो आंकडो",
    calcNumerator: "अंश",
    calcDenominator: "छेद",
    calcAdd: "बेरीज",
    calcSubtract: "वजाबाकी",
    calcMultiply: "गुणाकार",
    calcDivide: "भागाकार",
    calcShare: "वांटपाची रक्कम",
    calcMarked: "छापील किंमत",
    calcOff: "सूट %",
    calcRectangle: "आयत",
    calcSquare: "चौकोन",
    calcCircle: "वर्तुळ",
    calcTriangle: "त्रिकोण",
    calcLength: "लांबी",
    calcWidth: "रुंदी",
    calcSide: "बाजू",
    calcRadius: "त्रिज्या",
    calcBase: "पाया",
    calcHeight: "उंची",
    calcFindSpeed: "वेग काडात",
    calcFindDistance: "अंतर काडात",
    calcFindTime: "वेळ काडात",
    calcDistance: "अंतर (किमी)",
    calcTime: "वेळ (वरां)",
    calcSpeedValue: "वेग (किमी/वरा)",
    calcTableOf: "पाढो",
    resultInterest: "व्याज",
    resultAmount: "एकूण",
    resultProfit: "नफा",
    resultLoss: "तोटो",
    resultTotal: "एकूण",
    resultBase: "GST आदीं",
    resultMonthly: "दर म्हयनो",
    resultOff: "सूट",
    resultSale: "विक्री किंमत",
    resultArea: "क्षेत्रफळ",
    resultPerimeter: "परिमिती",
    resultYears: "वर्सां",
    resultMonths: "म्हयने",
    resultEach: "दर व्यक्ती",
    resultFactors: "अवयव",
    resultSquare: "वर्ग",
    resultCube: "घन",
    resultRoman: "रोमन",
    timer: "अभ्यासाचो वेळ",
    timerNote: "हें फोनाचेर मेजतात. हाका संदेश लागतना.",
    timerMinutes: "मिनीट",
    timerStart: "सुरवात",
    timerPause: "थांबात",
    timerReset: "परत",
    timerDone: "वेळ सोपलो.",
    lofi: "लोफाय",
    musicRain: "पावस",
    musicPiano: "पियानो",
    musicWaves: "लहरां",
    musicNight: "रात",
    musicBells: "घांट",
    flashcards: "कार्ड",
    flashEmpty: "चुकिल्लें प्रश्न कार्ड जातले.",
    flashFlip: "उलटयात",
    shareHolidays: "सुट्ट्यो धाडात",
    textSize: "अक्षरांचो आकार",
    textSmall: "ल्हान",
    textMedium: "मध्यम",
    textLarge: "व्हड",
    missed: "हें परत विचारात",
    emptyMissed: "चुकिल्लें प्रश्न हांगा दिसतले.",
    retryMiss: "हो प्रश्न परत घेयात",
    deleteMiss: "प्रश्न काडात",
    holidays: "सुट्ट्यो",
    holidayNote: "2026 च्यो राष्ट्रीय सुट्ट्यो आनी गोंयच्या शाळेच्यो सुट्ट्यो.",
    shareNote: "नोट धाडात",
    printNote: "नोट छापात",
    note: "नोट सेव",
    noteSaved: "नोट सेव जालो",
    notes: "नोट",
    emptyNotes: "सेव केल्ले नोट हांगा दिसतले.",
    deleteNote: "नोट काडात",
    exportChat: "गप्प सेव करात",
    sources: "स्त्रोत",
    searchChats: "गप्पा सोदात",
    rename: "नांव बदलात",
    pin: "पिन",
    unpin: "पिन काडात",
    install: "फोनाचेर इंस्टॉल करात",
    installShort: "इंस्टॉल",
    installIos: "iPhone चेरी Share दामात, मागीर Add to Home Screen वेंचात.",
  },
  mr: {
    brand: "सुसेगाड",
    tagline: "इंग्रजी, हिंदी, हिंग्लिश, मराठी किंवा कोंकणीत विचारा.",
    mood: "गोव्याच्या एका सावकाश दुपारची जाणीव.",
    about: "भारतासाठी एक चॅट अ‍ॅप.",
    creditBefore: "",
    creditName: "लुकमान",
    creditAfter: " यांनी केले, इयत्ता 8, PM SHRI स्कूल काळाय, गोवा.",
    madeBefore: "",
    madeName: "लुकमान",
    madeStudio: "CoastalCode",
    madeAfter: " यांनी गोव्यात डिझाइन आणि डेव्हलप केले",
    newChat: "नवीन गप्पा",
    chats: "गप्पा",
    emptyTitle: "सुसेगाड कशी मदत करेल?",
    placeholder: "सुसेगाडला संदेश लिहा",
    send: "पाठवा",
    stop: "थांबा",
    delete: "गप्पा काढा",
    menu: "गप्पा उघडा",
    close: "बंद",
    back: "परत",
    language: "English",
    thinking: "सुसेगाड विचार करत आहे",
    busy: "सुसेगाड आता व्यस्त आहे. पुन्हा प्रयत्न करा.",
    unavailable: "सुसेगाड आता उपलब्ध नाही. पुन्हा प्रयत्न करा.",
    limitTitle: "आजची मर्यादा संपली",
    limitBody: "आजचे मोफत संदेश संपले. मर्यादा मध्यरात्री IST ला रीसेट होते.",
    tooLong: "हा संदेश खूप मोठा आहे. लहान करून पुन्हा पाठवा.",
    untitled: "नवीन गप्पा",
    you: "तुम्ही",
    footer: "मोफत संदेश मध्यरात्री IST ला रीसेट होतात",
    remaining: "आज {count} संदेश शिल्लक",
    copy: "कॉपी",
    copied: "कॉपी झाले",
    edit: "बदला",
    save: "सेव्ह",
    cancel: "रद्द",
    regenerate: "पुन्हा लिहा",
    followLabel: "पुढे विचारा",
    moreIdeas: "नवीन कल्पना",
    photo: "फोटो",
    listening: "ऐकत आहे",
    voice: "बोला",
    voiceStop: "आवाज थांबवा",
    voiceFailed: "आवाजाने लिहिणे Chrome किंवा Edge मध्ये चालते.",
    listen: "ऐका",
    listenStop: "थांबा",
    shorter: "लहान",
    classFive: "इयत्ता 5 सारखे",
    classFivePrompt: "तुमचे शेवटचे उत्तर इयत्ता 5 च्या विद्यार्थ्यासाठी समजावून सांगा. छोटी वाक्ये आणि एक सोपे उदाहरण द्या.",
    shorterPrompt: "हे पुन्हा कमी आणि सोप्या शब्दांत सांगा.",
    otherLanguage: "हिंदी",
    translatePrompt: "तुमचे शेवटचे उत्तर हिंदीत लिहा.",
    whatsapp: "WhatsApp",
    draw: "चित्र",
    drawing: "चित्र तयार होत आहे",
    drawReady: "हे घ्या चित्र.",
    drawFailed: "चित्र पूर्ण झाले नाही. पुन्हा प्रयत्न करा.",
    imageLimit: "आजची मोफत चित्रे संपली. मर्यादा मध्यरात्री IST ला रीसेट होते.",
    drawPlaceholder: "चित्राचे वर्णन लिहा",
    photoFailed: "लहान फोटो निवडून पुन्हा प्रयत्न करा.",
    lookPrompt: "हे चित्र पहा.",
    download: "डाउनलोड",
    quiz: "प्रश्नमंजुषा",
    quizStart: "प्रश्नमंजुषा",
    quizStartTopic: "{topic} वर प्रश्नमंजुषा",
    quizPhoto: "या गृहपाठावर प्रश्नमंजुषा",
    quizOnThis: "यावर प्रश्नमंजुषा",
    quizPlaceholder: "प्रश्नमंजुषा कशाबद्दल हवी?",
    quizMaths: "गणित",
    quizScience: "विज्ञान",
    quizEnglish: "इंग्रजी",
    quizHindi: "हिंदी",
    quizGk: "सामान्य ज्ञान",
    quizQuestion: "प्रश्न {ask} / {total}",
    quizRight: "बरोबर",
    quizWrong: "चूक",
    quizDone: "प्रश्नमंजुषा संपली",
    quizScore: "{score} / {total}",
    quizHint: "सूचना",
    quizHideHint: "सूचना लपवा",
    quizClass5: "इयत्ता 5",
    quizClass8: "इयत्ता 8",
    quizClass10: "इयत्ता 10",
    shelf: "आणखी",
    quizTrueFalse: "खरे की खोटे",
    quizMissedAll: "चुकलेले पुन्हा घ्या",
    quizMissedTopic: "चुकलेले प्रश्न",
    scores: "प्रश्नमंजुषेचे गुण",
    emptyScores: "संपलेल्या प्रश्नमंजुषा येथे दिसतील.",
    calc: "कॅल्क्युलेटर",
    calcNote: "हे फोनवर मोजले जाते. याला संदेश लागत नाही.",
    calcShow: "दाखवा",
    calcCheck: "आकडे तपासा आणि पुन्हा प्रयत्न करा.",
    calcRupees: "रुपयांमध्ये शब्द",
    calcInterest: "सरळ व्याज",
    calcProfit: "नफा आणि तोटा",
    calcAverage: "सरासरी",
    calcGst: "GST",
    calcEmi: "EMI",
    calcCurrency: "चलन",
    calcFrom: "पासून",
    calcTo: "मध्ये",
    calcRateDate: "युरोपियन सेंट्रल बँक, {date}",
    calcRates: "दर आत्ता उपलब्ध नाहीत.",
    calcHcf: "HCF आणि LCM",
    calcFraction: "अपूर्णांक",
    calcRatio: "गुणोत्तर",
    calcDiscount: "सवलत",
    calcArea: "क्षेत्रफळ आणि परिमिती",
    calcSpeed: "वेग, अंतर, वेळ",
    calcTable: "पाढे",
    calcPercent: "टक्केवारी",
    calcAge: "वय",
    calcSplit: "बिल वाटा",
    calcUnits: "एकके",
    calcFactors: "अवयव",
    calcPowers: "वर्ग आणि घन",
    calcRoman: "रोमन अंक",
    calcPercentOf: "रकमेची टक्केवारी",
    calcWhatPercent: "किती टक्के",
    calcPart: "भाग",
    calcWhole: "पूर्ण",
    calcPeople: "लोक",
    calcTip: "टिप %",
    calcBirthday: "जन्म तारीख",
    calcUnitLength: "सेंटीमीटर आणि मीटर",
    calcUnitMass: "ग्रॅम आणि किलोग्राम",
    calcUnitVolume: "मिलिलिटर आणि लिटर",
    calcUnitTemp: "सेल्सियस आणि फॅरनहाइट",
    calcAmount: "रक्कम",
    calcPrincipal: "मुद्दल",
    calcRate: "दर %",
    calcYears: "वर्षे",
    calcMonths: "महिने",
    calcCost: "खरेदी किंमत",
    calcSelling: "विक्री किंमत",
    calcNumbers: "आकडे, स्वल्पविरामाने वेगळे",
    calcInclusive: "रकमेत GST समाविष्ट आहे",
    calcFirst: "पहिला आकडा",
    calcSecond: "दुसरा आकडा",
    calcNumerator: "अंश",
    calcDenominator: "छेद",
    calcAdd: "बेरीज",
    calcSubtract: "वजाबाकी",
    calcMultiply: "गुणाकार",
    calcDivide: "भागाकार",
    calcShare: "वाटण्याची रक्कम",
    calcMarked: "छापील किंमत",
    calcOff: "सवलत %",
    calcRectangle: "आयत",
    calcSquare: "चौरस",
    calcCircle: "वर्तुळ",
    calcTriangle: "त्रिकोण",
    calcLength: "लांबी",
    calcWidth: "रुंदी",
    calcSide: "बाजू",
    calcRadius: "त्रिज्या",
    calcBase: "पाया",
    calcHeight: "उंची",
    calcFindSpeed: "वेग काढा",
    calcFindDistance: "अंतर काढा",
    calcFindTime: "वेळ काढा",
    calcDistance: "अंतर (किमी)",
    calcTime: "वेळ (तास)",
    calcSpeedValue: "वेग (किमी/तास)",
    calcTableOf: "पाढा",
    resultInterest: "व्याज",
    resultAmount: "एकूण",
    resultProfit: "नफा",
    resultLoss: "तोटा",
    resultTotal: "एकूण",
    resultBase: "GST आधी",
    resultMonthly: "दर महिना",
    resultOff: "सवलत",
    resultSale: "विक्री किंमत",
    resultArea: "क्षेत्रफळ",
    resultPerimeter: "परिमिती",
    resultYears: "वर्षे",
    resultMonths: "महिने",
    resultEach: "प्रत्येक जण",
    resultFactors: "अवयव",
    resultSquare: "वर्ग",
    resultCube: "घन",
    resultRoman: "रोमन",
    timer: "अभ्यासाची वेळ",
    timerNote: "हे फोनवर मोजले जाते. याला संदेश लागत नाही.",
    timerMinutes: "मिनिटे",
    timerStart: "सुरू",
    timerPause: "थांबवा",
    timerReset: "पुन्हा",
    timerDone: "वेळ संपली.",
    lofi: "लोफाय",
    musicRain: "पाऊस",
    musicPiano: "पियानो",
    musicWaves: "लाटा",
    musicNight: "रात्र",
    musicBells: "घंटा",
    flashcards: "कार्ड",
    flashEmpty: "चुकलेले प्रश्न कार्ड होतील.",
    flashFlip: "उलटा",
    shareHolidays: "सुट्ट्या पाठवा",
    textSize: "अक्षरांचा आकार",
    textSmall: "लहान",
    textMedium: "मध्यम",
    textLarge: "मोठे",
    missed: "हे पुन्हा विचारा",
    emptyMissed: "चुकलेले प्रश्न येथे दिसतील.",
    retryMiss: "हा प्रश्न पुन्हा घ्या",
    deleteMiss: "प्रश्न काढा",
    holidays: "सुट्ट्या",
    holidayNote: "2026 च्या राष्ट्रीय सुट्ट्या आणि गोव्याच्या शाळेच्या सुट्ट्या.",
    shareNote: "नोट पाठवा",
    printNote: "नोट छापा",
    note: "नोट सेव्ह",
    noteSaved: "नोट सेव्ह झाला",
    notes: "नोट",
    emptyNotes: "सेव्ह केलेले नोट येथे दिसतील.",
    deleteNote: "नोट काढा",
    exportChat: "गप्पा सेव्ह करा",
    sources: "स्रोत",
    searchChats: "गप्पा शोधा",
    rename: "नाव बदला",
    pin: "पिन",
    unpin: "पिन काढा",
    install: "फोनवर इंस्टॉल करा",
    installShort: "इंस्टॉल",
    installIos: "iPhone वर Share दाबा, मग Add to Home Screen निवडा.",
  },
} as const;

export type Copy = (typeof copy)[Lang];
