export type Lang = "en" | "hi";

export const copy = {
  en: {
    brand: "Susegad",
    tagline: "Ask in English, Hindi, or Hinglish.",
    mood: "The slow, easy feeling of a Goan afternoon.",
    about: "A chat app for India.",
    creditBefore: "Made by ",
    creditName: "Luqman",
    creditAfter: ", Class 8, PM SHRI School Kalay, Goa.",
    madeBefore: "Designed and developed by ",
    madeName: "Luqman",
    madeStudio: "CoastalCode",
    madeAfter: " in Goa",
    newChat: "New chat",
    chats: "Chats",
    emptyTitle: "How can Susegad help?",
    placeholder: "Message Susegad",
    send: "Send",
    stop: "Stop",
    delete: "Delete chat",
    menu: "Open chats",
    close: "Close",
    language: "हिंदी",
    thinking: "Susegad is thinking",
    busy: "Susegad is busy. Please try again.",
    unavailable: "Susegad is unavailable right now. Please try again.",
    limitTitle: "Daily limit reached",
    limitBody:
      "You have used today's free messages. The limit resets at midnight IST.",
    tooLong: "That message is too long. Shorten it and try again.",
    untitled: "New chat",
    you: "You",
    footer: "Free messages reset at midnight IST",
    remaining: "{count} messages left today",
    copy: "Copy",
    copied: "Copied",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    regenerate: "Try again",
    followLabel: "Ask next",
    moreIdeas: "New ideas",
    photo: "Photo",
    listening: "Listening",
    voice: "Voice",
    voiceStop: "Stop voice",
    voiceFailed: "Voice typing works in Chrome or Edge.",
    listen: "Listen",
    listenStop: "Stop",
    shorter: "Shorter",
    shorterPrompt: "Say that again in fewer, simpler words.",
    otherLanguage: "In Hindi",
    translatePrompt: "Rewrite your last answer in Hindi.",
    whatsapp: "WhatsApp",
    draw: "Draw",
    drawing: "Drawing your picture",
    drawReady: "Here is the picture.",
    drawFailed: "The picture did not finish. Please try again.",
    imageLimit: "Today's free drawings are used up. They reset at midnight IST.",
    drawPlaceholder: "Describe a picture",
    photoFailed: "Choose a smaller photo and try again.",
    lookPrompt: "Look at this picture.",
    searchChats: "Search chats",
    rename: "Rename",
    pin: "Pin",
    unpin: "Unpin",
    install: "Install on your phone",
    installShort: "Install",
    installIos: "On iPhone, tap Share, then Add to Home Screen.",
  },
  hi: {
    brand: "सुसेगाद",
    tagline: "हिंदी, अंग्रेज़ी या हिंग्लिश में पूछें।",
    mood: "गोवा की एक धीमी, आसान दोपहर का एहसास।",
    about: "भारत के लिए एक चैट ऐप।",
    creditBefore: "",
    creditName: "लुकमान",
    creditAfter: " ने बनाया, कक्षा 8, PM SHRI स्कूल कालय, गोवा।",
    madeBefore: "",
    madeName: "लुकमान",
    madeStudio: "CoastalCode",
    madeAfter: " ने गोवा में डिज़ाइन और डेवलप किया",
    newChat: "नई बातचीत",
    chats: "बातचीत",
    emptyTitle: "सुसेगाद कैसे मदद करे?",
    placeholder: "सुसेगाद को संदेश लिखें",
    send: "भेजें",
    stop: "रोकें",
    delete: "बातचीत हटाएँ",
    menu: "बातचीत खोलें",
    close: "बंद करें",
    language: "English",
    thinking: "सुसेगाद सोच रहा है",
    busy: "सुसेगाद अभी व्यस्त है। फिर कोशिश करें।",
    unavailable: "सुसेगाद अभी उपलब्ध नहीं है। फिर कोशिश करें।",
    limitTitle: "आज की सीमा पूरी हो गई",
    limitBody:
      "आज के मुफ़्त संदेश खत्म हो गए। सीमा आधी रात IST पर रीसेट होती है।",
    tooLong: "यह संदेश बहुत लंबा है। छोटा करके फिर भेजें।",
    untitled: "नई बातचीत",
    you: "आप",
    footer: "मुफ़्त संदेश आधी रात IST पर रीसेट होते हैं",
    remaining: "आज {count} संदेश बचे हैं",
    copy: "कॉपी",
    copied: "कॉपी हो गया",
    edit: "बदलें",
    save: "सहेजें",
    cancel: "रद्द",
    regenerate: "फिर से लिखो",
    followLabel: "आगे पूछें",
    moreIdeas: "नए सुझाव",
    photo: "फोटो",
    listening: "सुन रहा है",
    voice: "बोलें",
    voiceStop: "आवाज़ रोकें",
    voiceFailed: "आवाज़ से लिखना Chrome या Edge में चलता है।",
    listen: "सुनो",
    listenStop: "रोकें",
    shorter: "छोटा",
    shorterPrompt: "इसे फिर से कम और आसान शब्दों में कहो।",
    otherLanguage: "English",
    translatePrompt: "अपना पिछला जवाब अंग्रेज़ी में लिखो।",
    whatsapp: "WhatsApp",
    draw: "चित्र",
    drawing: "चित्र बन रहा है",
    drawReady: "यह रही तस्वीर।",
    drawFailed: "चित्र पूरा नहीं हुआ। फिर कोशिश करें।",
    imageLimit: "आज के मुफ़्त चित्र खत्म हो गए। सीमा आधी रात IST पर रीसेट होती है।",
    drawPlaceholder: "चित्र का वर्णन लिखें",
    photoFailed: "छोटी फोटो चुनकर फिर कोशिश करें।",
    lookPrompt: "इस तस्वीर को देखो।",
    searchChats: "बातचीत खोजें",
    rename: "नाम बदलें",
    pin: "पिन",
    unpin: "पिन हटाएँ",
    install: "फ़ोन पर इंस्टॉल करें",
    installShort: "इंस्टॉल",
    installIos: "iPhone पर Share दबाएँ, फिर Add to Home Screen चुनें।",
  },
} as const;

export type Copy = (typeof copy)[Lang];
