export type Lang = "en" | "hi";

export const copy = {
  en: {
    brand: "Goan AI",
    tagline: "Ask in English, Hindi, or Hinglish.",
    about: "A chat app for India.",
    creditBefore: "Made by ",
    creditName: "Luqman",
    creditAfter: ", Class 8, PM SHRI School Kalay, Goa.",
    madeBefore: "Designed and developed by ",
    madeName: "Luqman",
    madeStudio: "CoastalCode",
    madeAfter: " in Goa",
    newChat: "New chat",
    chats: "Chats",
    emptyTitle: "How can Goan AI help?",
    placeholder: "Message Goan AI",
    send: "Send",
    stop: "Stop",
    delete: "Delete chat",
    menu: "Open chats",
    close: "Close",
    language: "हिंदी",
    thinking: "Goan AI is thinking",
    busy: "Goan AI is busy. Please try again.",
    unavailable: "This model is unavailable right now. Choose another model.",
    limitTitle: "Daily limit reached",
    limitBody:
      "You have used today's free messages. The limit resets at midnight IST.",
    tooLong: "That message is too long. Shorten it and try again.",
    untitled: "New chat",
    you: "You",
    footer: "Free messages reset at midnight IST",
    remaining: "{count} messages left today",
    copy: "Copy",
    copied: "Copied",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    regenerate: "Try again",
    followLabel: "Ask next",
    moreIdeas: "New ideas",
    install: "Install on your phone",
    installShort: "Install",
    installIos: "On iPhone, tap Share, then Add to Home Screen.",
  },
  hi: {
    brand: "गोवन AI",
    tagline: "हिंदी, अंग्रेज़ी या हिंग्लिश में पूछें।",
    about: "भारत के लिए एक चैट ऐप।",
    creditBefore: "",
    creditName: "लुकमान",
    creditAfter: " ने बनाया, कक्षा 8, PM SHRI स्कूल कालय, गोवा।",
    madeBefore: "",
    madeName: "लुकमान",
    madeStudio: "CoastalCode",
    madeAfter: " ने गोवा में डिज़ाइन और डेवलप किया",
    newChat: "नई बातचीत",
    chats: "बातचीत",
    emptyTitle: "गोवन AI कैसे मदद करे?",
    placeholder: "गोवन AI को संदेश लिखें",
    send: "भेजें",
    stop: "रोकें",
    delete: "बातचीत हटाएँ",
    menu: "बातचीत खोलें",
    close: "बंद करें",
    language: "English",
    thinking: "गोवन AI सोच रहा है",
    busy: "गोवन AI अभी व्यस्त है। फिर कोशिश करें।",
    unavailable: "यह मॉडल अभी उपलब्ध नहीं है। दूसरा मॉडल चुनें।",
    limitTitle: "आज की सीमा पूरी हो गई",
    limitBody:
      "आज के मुफ़्त संदेश खत्म हो गए। सीमा आधी रात IST पर रीसेट होती है।",
    tooLong: "यह संदेश बहुत लंबा है। छोटा करके फिर भेजें।",
    untitled: "नई बातचीत",
    you: "आप",
    footer: "मुफ़्त संदेश आधी रात IST पर रीसेट होते हैं",
    remaining: "आज {count} संदेश बचे हैं",
    copy: "कॉपी",
    copied: "कॉपी हो गया",
    edit: "बदलें",
    save: "सहेजें",
    cancel: "रद्द",
    regenerate: "फिर से लिखो",
    followLabel: "आगे पूछें",
    moreIdeas: "नए सुझाव",
    install: "फ़ोन पर इंस्टॉल करें",
    installShort: "इंस्टॉल",
    installIos: "iPhone पर Share दबाएँ, फिर Add to Home Screen चुनें।",
  },
} as const;

export type Copy = (typeof copy)[Lang];
