"use client";

import { useSyncExternalStore } from "react";

import type { Lang } from "@/lib/copy";

export const promptIdeas = [
  { en: "Explain UPI in simple words", hi: "UPI को आसान हिंदी में समझाओ" },
  { en: "Plan a weekend in Jaipur", hi: "जयपुर में वीकेंड का प्लान बनाओ" },
  { en: "Write a polite email to my landlord", hi: "मकान मालिक को एक विनम्र ईमेल लिखो" },
  { en: "Explain GST in simple words", hi: "GST को आसान शब्दों में समझाओ" },
  { en: "Plan a weekend in Goa", hi: "गोवा में वीकेंड का प्लान बनाओ" },
  { en: "Write a polite message to my teacher", hi: "टीचर को एक विनम्र संदेश लिखो" },
  { en: "Explain a PAN card in simple words", hi: "PAN कार्ड को आसान शब्दों में समझाओ" },
  { en: "Plan a two-day trip to Agra", hi: "आगरा की दो दिन की यात्रा बनाओ" },
  { en: "Write a polite email asking for leave", hi: "छुट्टी माँगने का विनम्र ईमेल लिखो" },
  { en: "Explain Aadhaar in simple words", hi: "आधार को आसान शब्दों में समझाओ" },
  { en: "Plan a weekend in Udaipur", hi: "उदयपुर में वीकेंड का प्लान बनाओ" },
  { en: "Write a thank-you note to my neighbour", hi: "पड़ोसी को धन्यवाद का संदेश लिखो" },
  { en: "Explain FASTag in simple words", hi: "FASTag को आसान शब्दों में समझाओ" },
  { en: "Plan a family trip to Kerala", hi: "केरल की पारिवारिक यात्रा बनाओ" },
  { en: "Write a polite complaint about a late delivery", hi: "देर से डिलीवरी की विनम्र शिकायत लिखो" },
  { en: "Explain income tax in simple words", hi: "इनकम टैक्स को आसान शब्दों में समझाओ" },
  { en: "Plan a weekend in Manali", hi: "मनाली में वीकेंड का प्लान बनाओ" },
  { en: "Write a message to postpone a meeting", hi: "मीटिंग टालने का संदेश लिखो" },
  { en: "Explain mutual funds in simple words", hi: "म्यूचुअल फंड को आसान शब्दों में समझाओ" },
  { en: "Plan a day in Varanasi", hi: "वाराणसी में एक दिन का प्लान बनाओ" },
  { en: "Write a polite email to my boss", hi: "बॉस को एक विनम्र ईमेल लिखो" },
  { en: "Explain a SIP in simple words", hi: "SIP को आसान शब्दों में समझाओ" },
  { en: "Plan a weekend in Pondicherry", hi: "पुदुचेरी में वीकेंड का प्लान बनाओ" },
  { en: "Write an apology for missing class", hi: "क्लास मिस करने की माफी लिखो" },
  { en: "Explain credit score in simple words", hi: "क्रेडिट स्कोर को आसान शब्दों में समझाओ" },
  { en: "Plan a trip to the Golden Temple", hi: "स्वर्ण मंदिर की यात्रा का प्लान बनाओ" },
  { en: "Write a rent reminder that stays polite", hi: "किराए का विनम्र रिमाइंडर लिखो" },
  { en: "Explain NEFT, IMPS, and RTGS simply", hi: "NEFT, IMPS और RTGS का फर्क समझाओ" },
  { en: "Plan a rainy weekend in Mumbai", hi: "मुंबई में बारिश वाले वीकेंड का प्लान बनाओ" },
  { en: "Write a polite review of a restaurant", hi: "रेस्टोरेंट की विनम्र समीक्षा लिखो" },
  { en: "Explain health insurance in simple words", hi: "हेल्थ इंश्योरेंस को आसान शब्दों में समझाओ" },
  { en: "Plan a weekend in Hampi", hi: "हंपी में वीकेंड का प्लान बनाओ" },
  { en: "Write a message asking for a fee receipt", hi: "फीस रसीद माँगने का संदेश लिखो" },
  { en: "Explain EPF in simple words", hi: "EPF को आसान शब्दों में समझाओ" },
  { en: "Plan a short trip to Rishikesh", hi: "ऋषिकेश की छोटी यात्रा बनाओ" },
  { en: "Write a polite email to the school principal", hi: "प्रिंसिपल को एक विनम्र ईमेल लिखो" },
  { en: "Explain DigiLocker in simple words", hi: "DigiLocker को आसान शब्दों में समझाओ" },
  { en: "Plan a food tour in Delhi", hi: "दिल्ली का फ़ूड टूर बनाओ" },
  { en: "Write a WhatsApp message to a client", hi: "क्लाइंट के लिए WhatsApp संदेश लिखो" },
  { en: "Explain inflation in simple words", hi: "महंगाई को आसान शब्दों में समझाओ" },
  { en: "Plan a weekend in Coorg", hi: "कूर्ग में वीकेंड का प्लान बनाओ" },
  { en: "Write a polite follow-up after an interview", hi: "इंटरव्यू के बाद विनम्र फॉलो-अप लिखो" },
  { en: "Explain compound interest with an example", hi: "चक्रवृद्धि ब्याज एक उदाहरण से समझाओ" },
  { en: "Plan a beach day in Gokarna", hi: "गोकर्ण में बीच वाले दिन का प्लान बनाओ" },
  { en: "Write a notice for a housing society meeting", hi: "सोसाइटी मीटिंग का नोटिस लिखो" },
  { en: "Explain the difference between an FD and an RD", hi: "FD और RD का फर्क समझाओ" },
  { en: "Plan a heritage walk in Ahmedabad", hi: "अहमदाबाद की हेरिटेज वॉक बनाओ" },
  { en: "Write a polite email to return a product", hi: "सामान वापस करने का विनम्र ईमेल लिखो" },
  { en: "Explain how a home loan EMI works", hi: "होम लोन की EMI कैसे बनती है, समझाओ" },
  { en: "Plan a winter weekend in Shimla", hi: "शिमला में सर्दियों के वीकेंड का प्लान बनाओ" },
  { en: "Write a birthday wish for my grandmother", hi: "दादी के लिए जन्मदिन की शुभकामना लिखो" },
  { en: "Explain net banking in simple words", hi: "नेट बैंकिंग को आसान शब्दों में समझाओ" },
  { en: "Plan a trip to the Sundarbans", hi: "सुंदरबन की यात्रा का प्लान बनाओ" },
  { en: "Write a polite request for a salary slip", hi: "सैलरी स्लिप माँगने का विनम्र ईमेल लिखो" },
  { en: "Explain how to read an electricity bill", hi: "बिजली का बिल कैसे पढ़ें, समझाओ" },
  { en: "Plan a weekend in Mysuru", hi: "मैसूर में वीकेंड का प्लान बनाओ" },
  { en: "Write an email asking a doctor to reschedule", hi: "डॉक्टर से समय बदलने का ईमेल लिखो" },
  { en: "Explain a monthly budget in simple words", hi: "महीने का बजट आसान शब्दों में समझाओ" },
  { en: "Plan a one-day trip from Pune", hi: "पुणे से एक दिन की यात्रा बनाओ" },
  { en: "Write a polite message to a noisy neighbour", hi: "शोर करने वाले पड़ोसी को विनम्र संदेश लिखो" },
  { en: "Explain how a UPI PIN and an OTP differ", hi: "UPI PIN और OTP का फर्क समझाओ" },
  { en: "Plan a weekend in Darjeeling", hi: "दार्जिलिंग में वीकेंड का प्लान बनाओ" },
  { en: "Write a cover letter for a fresher job", hi: "फ्रेशर जॉब के लिए कवर लेटर लिखो" },
  { en: "Explain how to file a simple tax return", hi: "आसान इनकम टैक्स रिटर्न कैसे भरें, समझाओ" },
  { en: "Plan a temple trail in Tamil Nadu", hi: "तमिलनाडु के मंदिरों की यात्रा बनाओ" },
  { en: "Write a polite email to my professor", hi: "प्रोफेसर को एक विनम्र ईमेल लिखो" },
  { en: "Explain shares in simple words", hi: "शेयर बाज़ार को आसान शब्दों में समझाओ" },
  { en: "Plan a street-food evening in Lucknow", hi: "लखनऊ की स्ट्रीट फ़ूड शाम बनाओ" },
  { en: "Write a resignation letter that stays kind", hi: "नम्र इस्तीफे का पत्र लिखो" },
  { en: "Explain how to compare two mobile plans", hi: "दो मोबाइल प्लान की तुलना कैसे करें, समझाओ" },
  { en: "Plan a weekend in Jaisalmer", hi: "जैसलमेर में वीकेंड का प्लान बनाओ" },
  { en: "Write a complaint about the water supply", hi: "पानी की समस्या की विनम्र शिकायत लिखो" },
  { en: "Explain Ayushman Bharat in simple words", hi: "आयुष्मान भारत को आसान शब्दों में समझाओ" },
  { en: "Plan a quiet weekend in Munnar", hi: "मुन्नार में शांत वीकेंड का प्लान बनाओ" },
  { en: "Write a thank-you email after an internship", hi: "इंटर्नशिप के बाद धन्यवाद ईमेल लिखो" },
  { en: "Explain section 80C in simple words", hi: "सेक्शन 80C को आसान शब्दों में समझाओ" },
  { en: "Plan a weekend in Shillong", hi: "शिलांग में वीकेंड का प्लान बनाओ" },
  { en: "Write a polite reminder for pending fees", hi: "बाकी फीस का विनम्र रिमाइंडर लिखो" },
  { en: "Explain debit and credit cards simply", hi: "डेबिट और क्रेडिट कार्ड का फर्क समझाओ" },
  { en: "Plan a sunrise trip to Kanyakumari", hi: "कन्याकुमारी में सूर्योदय की यात्रा बनाओ" },
  { en: "Write an out-of-office message", hi: "ऑफिस से बाहर होने का संदेश लिखो" },
  { en: "Explain how to spot a fake UPI request", hi: "नकली UPI रिक्वेस्ट कैसे पहचानें, समझाओ" },
  { en: "Plan a handicraft walk in Jaipur", hi: "जयपुर की हस्तकला वॉक बनाओ" },
  { en: "Write a polite email to correct a train ticket", hi: "ट्रेन टिकट सुधारने का विनम्र ईमेल लिखो" },
  { en: "Explain PPF in simple words", hi: "PPF को आसान शब्दों में समझाओ" },
  { en: "Plan a weekend in Amritsar", hi: "अमृतसर में वीकेंड का प्लान बनाओ" },
  { en: "Write a kind message asking a friend to repay", hi: "दोस्त से पैसे वापस माँगने का विनम्र संदेश लिखो" },
  { en: "Explain a demat account in simple words", hi: "डीमैट खाता कैसे काम करता है, समझाओ" },
  { en: "Plan a hill trip to Ooty", hi: "ऊटी की पहाड़ी यात्रा बनाओ" },
  { en: "Write a polite email about a house repair", hi: "मरम्मत के लिए मकान मालिक को विनम्र ईमेल लिखो" },
  { en: "Explain NPS in simple words", hi: "NPS को आसान शब्दों में समझाओ" },
  { en: "Plan a market weekend in Kolkata", hi: "कोलकाता के बाज़ार वीकेंड का प्लान बनाओ" },
  { en: "Write a short speech for a school assembly", hi: "स्कूल असेंबली के लिए छोटा भाषण लिखो" },
  { en: "Explain how to read a nutrition label", hi: "न्यूट्रिशन लेबल कैसे पढ़ें, समझाओ" },
  { en: "Plan a backwater day in Alleppey", hi: "अल्लेप्पी में बैकवाटर का दिन बनाओ" },
  { en: "Write a polite email asking for a recommendation", hi: "सिफारिश माँगने का विनम्र ईमेल लिखो" },
  { en: "Explain a recurring deposit with an example", hi: "रिकरिंग डिपॉज़िट एक उदाहरण से समझाओ" },
  { en: "Plan a festival weekend in Pushkar", hi: "पुष्कर के मेले वाले वीकेंड का प्लान बनाओ" },
  { en: "Write a message to confirm a cab booking", hi: "कैब बुकिंग कन्फर्म करने का संदेश लिखो" },
  { en: "Plan a student budget for one month", hi: "छात्र के एक महीने का बजट बनाओ" },
  { en: "Make a revision plan for tomorrow's test", hi: "कल की परीक्षा के लिए रिवीजन प्लान बनाओ" },
  { en: "Explain photosynthesis in simple words", hi: "प्रकाश संश्लेषण को आसान शब्दों में समझाओ" },
  { en: "Quiz me with five fraction questions", hi: "भिन्न पर पाँच सवालों की क्विज़ लो" },
  { en: "Write a paragraph about my favourite festival", hi: "मेरे पसंदीदा त्योहार पर एक पैराग्राफ लिखो" },
  { en: "Help me choose a simple science project", hi: "एक आसान साइंस प्रोजेक्ट चुनने में मदद करो" },
  { en: "Explain the water cycle with an example", hi: "जल चक्र एक उदाहरण से समझाओ" },
  { en: "Make flashcards for states and capitals", hi: "राज्य और राजधानी के फ्लैशकार्ड बनाओ" },
  { en: "Plan one hour of homework for tonight", hi: "आज रात के एक घंटे का होमवर्क प्लान बनाओ" },
  { en: "Explain democracy in simple words", hi: "लोकतंत्र को आसान शब्दों में समझाओ" },
  { en: "Write five questions on the freedom struggle", hi: "स्वतंत्रता संग्राम पर पाँच सवाल लिखो" },
  { en: "Make a weekly cleaning list for my room", hi: "मेरे कमरे की हफ्ते की सफाई सूची बनाओ" },
  { en: "Plan simple dinners for five weekdays", hi: "पाँच काम के दिनों का आसान डिनर प्लान बनाओ" },
  { en: "Write a grocery list for a family of four", hi: "चार लोगों के परिवार की किराने की सूची लिखो" },
  { en: "Explain how to save electricity at home", hi: "घर पर बिजली कैसे बचाएँ, समझाओ" },
  { en: "Make a morning routine for school days", hi: "स्कूल वाले दिनों की सुबह की दिनचर्या बनाओ" },
  { en: "Plan a healthy tiffin for school", hi: "स्कूल के लिए हेल्दी टिफिन का प्लान बनाओ" },
  { en: "Explain how to remove a tea stain", hi: "चाय का दाग कैसे हटाएँ, समझाओ" },
  { en: "Write a checklist before I leave home", hi: "घर से निकलने से पहले की चेकलिस्ट लिखो" },
  { en: "Plan a rainy day at home", hi: "घर पर बरसात वाले दिन का प्लान बनाओ" },
  { en: "Explain how to keep vegetables fresh", hi: "सब्ज़ियाँ ताज़ा कैसे रखें, समझाओ" },
  { en: "Explain how to split a restaurant bill", hi: "रेस्टोरेंट का बिल बाँटना आसान शब्दों में समझाओ" },
  { en: "Make a pocket-money plan for one week", hi: "एक हफ्ते के पॉकेट मनी का प्लान बनाओ" },
  { en: "Explain what a savings account is", hi: "सेविंग्स अकाउंट क्या होता है, समझाओ" },
  { en: "Explain how to read a bank SMS", hi: "बैंक का SMS कैसे पढ़ें, समझाओ" },
  { en: "Compare two prices and pick the better buy", hi: "दो कीमतों की तुलना करके बेहतर खरीद बताओ" },
  { en: "Write a polite SMS to say I will be late", hi: "देर से पहुँचने का विनम्र SMS लिखो" },
  { en: "Write a get-well message for a classmate", hi: "सहपाठी के लिए जल्द ठीक होने का संदेश लिखो" },
  { en: "Write a thank-you message to my coach", hi: "कोच को धन्यवाद का संदेश लिखो" },
  { en: "Write a message asking for today's notes", hi: "आज के नोट्स माँगने का संदेश लिखो" },
  { en: "Write a birthday message for my father", hi: "पापा के लिए जन्मदिन का संदेश लिखो" },
  { en: "Write an invitation for a birthday at home", hi: "घर पर जन्मदिन का निमंत्रण लिखो" },
  { en: "Write a sorry message for a missed call", hi: "मिस्ड कॉल के लिए माफी का संदेश लिखो" },
  { en: "Write a message to say I reached home", hi: "घर पहुँच गया, ऐसा संदेश लिखो" },
  { en: "Write a polite reminder to return my book", hi: "किताब वापस माँगने का विनम्र रिमाइंडर लिखो" },
  { en: "Write a short thank-you note to my parents", hi: "माता-पिता को छोटा धन्यवाद नोट लिखो" },
  { en: "Make a water-drinking plan for a school day", hi: "स्कूल वाले दिन का पानी पीने का प्लान बनाओ" },
  { en: "Explain why sleep matters before an exam", hi: "परीक्षा से पहले नींद क्यों ज़रूरी है, समझाओ" },
  { en: "Plan a 20-minute evening walk", hi: "शाम की 20 मिनट की सैर का प्लान बनाओ" },
  { en: "Explain a balanced Indian meal simply", hi: "संतुलित भारतीय थाली आसान शब्दों में समझाओ" },
  { en: "Make a screen-time plan for school nights", hi: "स्कूल वाली रातों का स्क्रीन-टाइम प्लान बनाओ" },
  { en: "Explain how to pay an electricity bill on UPI", hi: "UPI से बिजली का बिल कैसे भरें, समझाओ" },
  { en: "Explain how to track a courier parcel", hi: "कूरियर पार्सल कैसे ट्रैक करें, समझाओ" },
  { en: "Explain how a ration card is used", hi: "राशन कार्ड कैसे इस्तेमाल होता है, समझाओ" },
  { en: "Explain how to recharge a prepaid mobile", hi: "प्रीपेड मोबाइल रिचार्ज कैसे करें, समझाओ" },
  { en: "Explain how to check a train PNR status", hi: "ट्रेन का PNR स्टेटस कैसे देखें, समझाओ" },
  { en: "Explain how to book a bus ticket online", hi: "ऑनलाइन बस टिकट कैसे बुक करें, समझाओ" },
  { en: "Explain how to read a cooking-gas bill", hi: "गैस का बिल कैसे पढ़ें, समझाओ" },
  { en: "Explain how a metro card works", hi: "मेट्रो कार्ड कैसे काम करता है, समझाओ" },
  { en: "Explain how to find a nearby post office", hi: "पास का डाकघर कैसे ढूँढें, समझाओ" },
  { en: "Explain how to fill a bank deposit slip", hi: "बैंक डिपॉज़िट स्लिप कैसे भरें, समझाओ" },
  { en: "Plan a simple dal and rice dinner", hi: "आसान दाल-चावल डिनर का प्लान बनाओ" },
  { en: "Explain how to cook jeera rice", hi: "जीरा राइस कैसे बनाएँ, समझाओ" },
  { en: "Plan a Sunday breakfast for my family", hi: "परिवार के लिए रविवार के नाश्ते का प्लान बनाओ" },
  { en: "Make a list of easy monsoon snacks", hi: "आसान मॉनसून स्नैक्स की सूची बनाओ" },
  { en: "Explain curd and buttermilk simply", hi: "दही और छाछ का फर्क आसान शब्दों में समझाओ" },
  { en: "Plan a no-cook lunch for a hot day", hi: "गर्म दिन के लिए बिना पकाए लंच का प्लान बनाओ" },
  { en: "Explain how to boil milk safely", hi: "दूध सुरक्षित तरीके से कैसे उबालें, समझाओ" },
  { en: "Make a weekly fruit plan on a small budget", hi: "कम बजट में हफ्ते का फल प्लान बनाओ" },
  { en: "Explain how to store leftover roti", hi: "बची हुई रोटी कैसे रखें, समझाओ" },
  { en: "Plan a festive sweet with few ingredients", hi: "कम सामग्री वाली मिठाई का प्लान बनाओ" },
  { en: "Explain the Pomodoro method for homework", hi: "होमवर्क के लिए पोमोडोरो तरीका समझाओ" },
  { en: "Help me outline a history answer", hi: "इतिहास के जवाब की रूपरेखा बनाने में मदद करो" },
  { en: "Explain how to take clearer class notes", hi: "क्लास के साफ नोट्स कैसे लिखें, समझाओ" },
  { en: "Make a one-week plan to speak more English", hi: "ज़्यादा अंग्रेज़ी बोलने का एक हफ्ते का प्लान बनाओ" },
  { en: "Explain how to revise without only rereading", hi: "सिर्फ दोबारा पढ़े बिना रिवीजन कैसे करें, समझाओ" },
  { en: "Write a timetable from 4 pm to 9 pm", hi: "शाम 4 बजे से 9 बजे तक टाइमटेबल लिखो" },
  { en: "Explain what a topic sentence is", hi: "टॉपिक सेंटेंस क्या होता है, समझाओ" },
  { en: "Help me turn points into a paragraph", hi: "पॉइंट्स को पैराग्राफ में बदलने में मदद करो" },
  { en: "Make a checklist for exam morning", hi: "परीक्षा वाली सुबह की चेकलिस्ट बनाओ" },
  { en: "Explain how to learn spellings faster", hi: "स्पेलिंग जल्दी कैसे याद करें, समझाओ" },
  { en: "Write a notice for a lost water bottle", hi: "खोई पानी की बोतल का नोटिस लिखो" },
  { en: "Write a class duty list for one week", hi: "एक हफ्ते की क्लास ड्यूटी सूची लिखो" },
  { en: "Explain how to introduce myself in a new class", hi: "नई क्लास में अपना परिचय कैसे दें, समझाओ" },
  { en: "Write a short vote of thanks", hi: "छोटा धन्यवाद प्रस्ताव लिखो" },
  { en: "Plan questions to ask on a school trip", hi: "स्कूल ट्रिप पर पूछने के सवाल बनाओ" },
  { en: "Write a caption for a science-fair photo", hi: "साइंस फेयर की फोटो के लिए कैप्शन लिखो" },
  { en: "Write a pledge for a cleanliness drive", hi: "स्वच्छता अभियान की शपथ लिखो" },
  { en: "Explain how a school election works", hi: "स्कूल चुनाव कैसे होता है, समझाओ" },
  { en: "Write a welcome note for a new classmate", hi: "नए सहपाठी के लिए स्वागत नोट लिखो" },
  { en: "Make a packing list for a school picnic", hi: "स्कूल पिकनिक की पैकिंग सूची बनाओ" },
  { en: "Explain how to stay safe on a school bus", hi: "स्कूल बस में सुरक्षित कैसे रहें, समझाओ" },
  { en: "Explain what to do with a suspicious link", hi: "संदिग्ध लिंक आए तो क्या करें, समझाओ" },
  { en: "Explain how to lock a phone with a PIN", hi: "फ़ोन को PIN से कैसे लॉक करें, समझाओ" },
  { en: "Write a message saying I reached school", hi: "स्कूल पहुँच गया, ऐसा संदेश लिखो" },
  { en: "Explain why I should not share an OTP", hi: "OTP किसी को क्यों नहीं बताना चाहिए, समझाओ" },
  { en: "Make a list of family emergency numbers", hi: "परिवार के इमरजेंसी नंबरों की सूची बनाओ" },
  { en: "Explain how to cross a busy road safely", hi: "व्यस्त सड़क सुरक्षित कैसे पार करें, समझाओ" },
  { en: "Explain what I should not post about myself", hi: "अपने बारे में क्या ऑनलाइन नहीं डालना चाहिए, समझाओ" },
  { en: "Plan what to pack for a humid day", hi: "उमस वाले दिन के लिए पैकिंग प्लान बनाओ" },
  { en: "Explain the monsoon in simple words", hi: "मानसून को आसान शब्दों में समझाओ" },
  { en: "Plan an indoor games evening", hi: "घर के अंदर खेलों वाली शाम का प्लान बनाओ" },
  { en: "Make a checklist for a power cut", hi: "बिजली कटने की चेकलिस्ट बनाओ" },
  { en: "Explain how to dry clothes in the rain", hi: "बारिश में कपड़े कैसे सुखाएँ, समझाओ" },
  { en: "Plan a 10-minute stretch after class", hi: "क्लास के बाद 10 मिनट स्ट्रेच का प्लान बनाओ" },
  { en: "Help me understand a cricket scorecard", hi: "क्रिकेट स्कोरकार्ड समझाने में मदद करो" },
  { en: "Help me write a journal entry about today", hi: "आज की डायरी एंट्री लिखने में मदद करो" },
  { en: "Explain a map scale in simple words", hi: "नक्शे का स्केल आसान शब्दों में समझाओ" },
  { en: "Make a list of words I can use instead of very", hi: "very की जगह इस्तेमाल करने वाले शब्द बताओ" },
  { en: "Explain how a library card works", hi: "लाइब्रेरी कार्ड कैसे काम करता है, समझाओ" },
  { en: "Plan tomorrow from waking up to bedtime", hi: "कल सुबह उठने से सोने तक का प्लान बनाओ" },
] as const;

const none: number[] = [];
const listeners = new Set<() => void>();
let shown: number[] | null = null;

function subscribe(listener: () => void) {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

function draw(skip: ReadonlySet<number>) {
  const bag = promptIdeas.map((_, index) => index).filter((index) => !skip.has(index));
  for (let index = bag.length - 1; index > 0; index -= 1) {
    const swap = Math.floor(Math.random() * (index + 1));
    const current = bag[index];
    bag[index] = bag[swap];
    bag[swap] = current;
  }
  return bag.slice(0, 3);
}

function pickThree() {
  if (!shown) shown = draw(new Set());
  return shown;
}

export function shuffleStarterPrompts() {
  shown = draw(new Set(shown ?? []));
  listeners.forEach((listener) => listener());
}

export function useStarterPrompts(lang: Lang) {
  const indices = useSyncExternalStore(subscribe, pickThree, () => none);
  return indices.map((index) => promptIdeas[index][lang]);
}
